# Generated by Django 3.2.3 on 2021-07-11 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testsuits',
            fields=[
                ('id', models.BigAutoField(help_text='主键ID', primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('name', models.CharField(help_text='套件名称', max_length=100, unique=True, verbose_name='套件名称')),
                ('include', models.TextField(help_text='包含接口', verbose_name='包含接口')),
                ('project', models.ForeignKey(help_text='所属项目', on_delete=django.db.models.deletion.CASCADE, related_name='testsuits', to='projects.projects')),
            ],
            options={
                'verbose_name': '测试套件表',
                'verbose_name_plural': '测试套件表',
                'db_table': 'tb_testsuits',
            },
        ),
    ]
