# Generated by Django 3.2.3 on 2021-07-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(help_text='主键ID', primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('name', models.CharField(help_text='项目名称', max_length=100, unique=True, verbose_name='项目名称')),
                ('leader', models.CharField(blank=True, help_text='项目负责人', max_length=50, null=True, verbose_name='项目负责人')),
                ('developer', models.CharField(blank=True, help_text='开发人员', max_length=50, null=True, verbose_name='开发人员')),
                ('tester', models.CharField(blank=True, help_text='测试人员', max_length=50, null=True, verbose_name='测试人员')),
                ('is_build', models.BooleanField(default=False, help_text='是否构建', verbose_name='是否构建')),
                ('publish_app', models.CharField(help_text='发布应用', max_length=100, verbose_name='发布应用')),
                ('desc', models.TextField(blank=True, default='', help_text='项目描述', null=True, verbose_name='项目描述')),
            ],
            options={
                'verbose_name': '项目表',
                'verbose_name_plural': '项目表',
                'db_table': 'tb_projects',
            },
        ),
    ]
