# Generated by Django 3.2.3 on 2021-07-12 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='is_build',
        ),
    ]
