# Generated by Django 3.2.3 on 2021-07-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Envs',
            fields=[
                ('id', models.BigAutoField(help_text='主键ID', primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('name', models.CharField(help_text='环境名称', max_length=100, unique=True, verbose_name='环境名称')),
                ('base_url', models.URLField(help_text='base_url', verbose_name='base_url')),
                ('desc', models.CharField(help_text='描述', max_length=200, verbose_name='描述')),
            ],
            options={
                'verbose_name': '环境信息',
                'verbose_name_plural': '环境信息',
                'db_table': 'tb_envs',
            },
        ),
    ]
