# Generated by Django 3.2.3 on 2021-07-12 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configures', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configures',
            old_name='request_info',
            new_name='request',
        ),
    ]
