# Generated by Django 3.2.3 on 2021-07-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcases',
            old_name='request_info',
            new_name='request',
        ),
        migrations.AlterField(
            model_name='testcases',
            name='teardown',
            field=models.TextField(blank=True, default='', help_text='用例后置', null=True, verbose_name='用例后置'),
        ),
    ]
