# Generated by Django 3.2.3 on 2021-07-11 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebugTalks',
            fields=[
                ('id', models.BigAutoField(help_text='主键ID', primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('name', models.CharField(default='debugtalk.py', help_text='debugtalk文件名称', max_length=100, verbose_name='debugtalk文件名称')),
                ('debugtalk', models.TextField(default='#debugtalk.py', help_text='debugtalk.py文件', null=True)),
                ('project', models.OneToOneField(help_text='所属项目', on_delete=django.db.models.deletion.CASCADE, related_name='debugtalks', to='projects.projects')),
            ],
            options={
                'verbose_name': 'debugtalk.py文件',
                'verbose_name_plural': 'debugtalk.py文件',
                'db_table': 'tb_debugtalks',
            },
        ),
    ]
